### PR TITLE
Upgrade dependencies

### LINKED ISSUE #195: Outdated Dependencies
Some of the dependencies are quite outdated. As far as I see, the dependencies haven't changed a lot but contain significant improvements (ESM support, Node 18 support, React 18 support, ...) and fix a couple of errors currently shown to us.

It'd be great if you couple update the dependencies for us, especially `react-dnd`, `react-dnd-html5-backend`, `react-dnd-multi-backend`, `react-dnd-touch-backend` and `uuid`.

Let me know if you need any help. I'm willing to help out.

### PR DESCRIPTION
**Pull request by jtbandes**
#### Fixes #195

This is an attempt at addressing #195. The demo app seems to work, but I had a couple issues I'll need help with:

- Although the demo app uses React 18, when I tried switching from `ReactDOM.render()` to the newer `createRoot().render()` API to fix the deprecation warning, the initial attempt to drag a mosaic window didn't work. However, if I added a new tile before trying to drag, or just tried to drag twice, that did work as expected. Not sure what's going on there, but seems like it might be outside the scope of an upgrade so I left it as `ReactDOM.render()` for now.
- I wasn't able to run the unit tests locally:
  ```
  $ yarn test:unit
  yarn run v1.22.15
  $ mocha --opts test/mocha.opts 'test/*.ts'
  (node:90942) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
  (Use `node --trace-deprecation ...` to show where the warning was created)
  
  TypeError: Unknown file extension ".ts" for /Users/jacob/Desktop/react-mosaic/test/updatesSpec.ts
      at new NodeError (node:internal/errors:372:5)
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
      at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
      at defaultLoad (node:internal/modules/esm/load:21:20)
      at ESMLoader.load (node:internal/modules/esm/loader:407:26)
      at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
      at new ModuleJob (node:internal/modules/esm/module_job:66:26)
      at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Promise.all (index 0)
      at ESMLoader.import (node:internal/modules/esm/loader:385:24)
      at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
      at Object.exports.loadFilesAsync (/Users/jacob/Desktop/react-mosaic/node_modules/mocha/lib/esm-utils.js:28:20)
      at singleRun (/Users/jacob/Desktop/react-mosaic/node_modules/mocha/lib/cli/run-helpers.js:149:3)
      at exports.runMocha (/Users/jacob/Desktop/react-mosaic/node_modules/mocha/lib/cli/run-helpers.js:186:5)
      at Object.exports.handler (/Users/jacob/Desktop/react-mosaic/node_modules/mocha/lib/cli/run.js:319:5)
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  ```

#### Changes proposed in this pull request:

- Upgrade react-dnd and related packages. Required switching from react-dnd's HOC/decorator APIs to hooks (`useDrag`, `useDrop`) and `contextTypes` -> `useContext`.
- Upgrade webpack (because it was choking on a `??` token in a newer version of a dependency)

#### Reviewers should focus on:

- A couple minor changes to appease TypeScript, like `$set: null` -> `$set: undefined`, and addition of `!` in `mosaicActions.updateTree(createDragToUpdates(mosaicActions.getRoot()!, ownPath, destinationPath, position));`

- Changes to `export`ed components — some removals, and some changes from class to function components. Although some of these exports seem like they were only for HMR compatibility and not really intended to be part of the public API, this change may necessitate a major version bump to avoid breaking consumers who might've depended on them in some way.

#### Screenshot

N/A

### CODE REVIEW

**Comment by nomcopter** [comment]
Thanks for doing this! Will take a look soon. What dependency was webpack choking on? It is likely that package includes sources transpiled to more compatible ES versions that can be mapped to more easily with webpack aliases. Sounds like that went smoothly though so I'll give it a try soon.

**Comment by jtbandes** [comment]
Sorry, forgot which dependency it was exactly. You could probably just revert all the webpack changes and give it a quick try to find out if you're curious – but a webpack upgrade is probably due at some point anyway (although some webpack settings did have to change, so if you'd rather review those separately, maybe you can find some other way to work around the syntax errors with the old webpack version).

**Comment by jtbandes** [comment]
Hey @nomcopter, anything else I can help with here?

**Comment by nomcopter** [comment]
@jtbandes been pushing it forward over the past couple weeks between things - should actually have it ready today pending more webpack nonsense. Really appreciate the work you did and your patience 🙏

**Comment by jtbandes** [comment]
Yep, ESM hell might take the # 1 spot for biggest JS PITA even above the React 17->18 upgrade 😅

**Comment by nomcopter** [comment]
Seriously. Released! Let me know how it works for you https://github.com/nomcopter/react-mosaic/releases/tag/v6.0.0

**Pull request merged**
